coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 95%
        threshold: 2%
    patch:
      default:
        target: 90%
        threshold: 5%
comment:
  layout: "header, diff, flags, components"
  behavior: default
  require_changes: true
flags:
  coverage:
    paths:
      - src/
    carryforward: true
  local:
    paths:
      - src/
    carryforward: false
ignore:
  - "tests/**/*"
  - "benches/**/*"
  - "src/main.rs"
